equetzal/huronOS-build-tools

- base-system/base.sh
- base-system/prepare.sh
- base-system/usrroot/usr/lib/hos/enviroment.sh
- base-system/usrroot/usr/lib/hos/utils.sh
- base-system/usrroot/usr/lib/hsync/hsync.sh
- base-system/usrroot/usr/lib/hsync/libhapply.so
- base-system/usrroot/usr/lib/hsync/libhpersistence.so
- base-system/usrroot/usr/lib/systemd/system/happly-wallpaper.service
- base-system/usrroot/usr/sbin/hos-dmode
- base-system/usrroot/usr/sbin/hos-dvar
- base-system/usrroot/usr/sbin/hos-usb
- base-system/usrroot/usr/sbin/hos-wallpaper
> Modularize hsync

- base-system/tools/installer/install.sh
Rewrote how a device is selected (this fixes the "declare x not a valid identifier")
Rewrote how a device is erased (sometimes I got devices that weren't erased correctly / at all and ended with a mix of new files added + old files that were not properly erased),. After some tests this new erasing method prepares usbs (at least the ones I tested, about 11) with a 100% success ratio for the partitioning step
> Installer usb cleaning improvement

- base-system/tools/installer/install.sh
If a partition is mounted to a path that contains spaces, before the script threw an error because it didn't considered spaces in the path.
This fix takes the whole mount point path considering spaces.
> Fix error unmounting partitions

- base-system/tools/installer/install.sh
This PR adds to the installer the ability to receive the directives file URL and the directives server IP via command line arguments instead of being prompt for them. 
This can improve installation time and errors by minimizing typos and reusing previous command when using same terminal for consecutive installations.
Solves #82
> [Installer] Making directives data settable via arguments

- base-system/tools/installer/install.sh
During installation, we ask the system to flush the device before unmount to provide users with an status update of the process instead of leaving them stuck without information. 
Sadly, the installer was using [`sync`](https://linuxcommand.org/lc3_man_pages/sync1.html) alone which means the command will wait until **all the system buffers** are flushed. 
This PR changes `sync` to `sync -f [some_file_insite_syspart]` to only flush the filesystem of the target device instead of the full system. This reduces the installation time, and makes the installer more independent from other running installations on the system. Related to #84
Even if we're changing the `sync` to a single filesystem, somehow the `extlinux` installer do also wait for the system wide flush, leading the installed to wait …
> [Installer] Make flush device-specific

- base-system/usrroot/etc/hmm/all
- base-system/usrroot/etc/hmm/any
- software-modules/base/03-budgie/files/gnome-applications.menu
- software-modules/base/04-shared-libs/dependencies.txt
- software-modules/programming/neovim/neovim.desktop
- software-modules/programming/neovim/neovim.sh
> Adds neovim

- base-system/usrroot/etc/hmm/all
- base-system/usrroot/etc/hmm/any
- software-modules/base/04-shared-libs/dependencies.txt
- software-modules/debuggers/gdb/gdb.sh
Adding gdb
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/equetzal/huronOS-build-tools/pull/102).
* __->__ #102
* #101
> Adding gdb

- base-system/usrroot/etc/hmm/all
- base-system/usrroot/etc/hmm/any
- software-modules/base/04-shared-libs/dependencies.txt
- software-modules/debuggers/valgrind/valgrind.sh
Adding valgrind
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/equetzal/huronOS-build-tools/pull/103).
* __->__ #103
* #102
* #101
> Adding valgrind

- base-system/usrroot/etc/hmm/all
- base-system/usrroot/etc/hmm/any
- software-modules/base/03-budgie/files/gnome-applications.menu
- software-modules/base/04-shared-libs/dependencies.txt
- software-modules/debuggers/ddd/ddd.desktop
- software-modules/debuggers/ddd/ddd.sh
Adding ddd
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/equetzal/huronOS-build-tools/pull/104).
* __->__ #104
* #103
* #102
* #101
> Adding ddd

- base-system/usrroot/etc/hmm/all
- base-system/usrroot/etc/hmm/any
- software-modules/base/03-budgie/files/gnome-applications.menu
- software-modules/base/04-shared-libs/dependencies.txt
- software-modules/debuggers/visualvm/visualvm.desktop
- software-modules/debuggers/visualvm/visualvm.sh
Adding visualvm
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/equetzal/huronOS-build-tools/pull/105).
* __->__ #105
* #104
* #103
* #102
* #101
> Adding visualvm

- software-modules/langs/java/java-documentation.desktop
- software-modules/langs/java/java.sh
Adding the missing child (java)
> Adding the missing child (java)

- base-system/usrroot/usr/lib/hsync/libhfirewall.so
[#97] Hotfix for ipv6
This PR should be enough as a hotfix for #97.
> [#97] Hotfix for ipv6

- docs/start/requirements.md
[Documentation] Adding network requirements
> [Documentation] Adding network requirements

- software-modules/debuggers/ddd/ddd.sh
- software-modules/debuggers/gdb/gdb.sh
- software-modules/debuggers/valgrind/valgrind.sh
- software-modules/debuggers/visualvm/visualvm.sh
Fixing debuggers installers
Fixes some issues regarding the debuggers that resulted in problems at the time of executing them
> Fixing debuggers installers

- software-modules/programming/codeblocks/codeblocks.sh
- software-modules/programming/codeblocks/default.conf
Adds Codeblocks defaults (focuses on default terminal)
> Adds Codeblocks defaults (focuses on default terminal)

- docs/development/build-system.md
- docs/development/development-standards.md
- docs/development/how-to-create-a-build.md
- docs/development/repositories.md
- docs/development/source-control.md
- docs/development/tips-for-developing-huronOS.md
[Documentation] Adding source control
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/equetzal/huronOS-build-tools/pull/126).
* #127
* __->__ #126
> [Documentation] Adding source control

- docs/development/build-system.md
- docs/development/development-standards.md
- docs/development/documentation.md
- docs/development/how-to-contribute.md
- docs/development/how-to-create-a-build.md
- docs/development/release-system.md
- docs/development/repositories.md
- docs/development/tips-for-developing-huronOS.md
[Documentation] Adding intro to our repos
> [Documentation] Adding intro to our repos

- docs/development/repositories.md
Updating repositories docs to block-code the TODO mention
> Updating repositories docs to block-code the TODO mention

- docs/usage/syncing-instances.md
> Polishing sync docs

- base-system/tools/make-iso/make-iso.sh
Updates make-iso.sh
Updates the md5 hash generation so it doesn't override the sha256 hash
> Updates make-iso.sh

- .gitmodules
- docs/development/how-to-create-a-build.md
Added bookmark-bridge package submodule
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/equetzal/huronOS-build-tools/pull/158).
* #164
* #139
* #93
* __->__ #158
> Added bookmark-bridge package submodule

- software-modules/programming/sublime/sublime.sh
Updating sublime software files
This PR
* Updates sublime to download the .deb from apt instead of a local file in the software folder
> Updating sublime software files

- docs/usage/directives/directives-file-syntax.md
[Documentation] Fixing browser-bookmark in directives file syntax
> [Documentation] Fixing browser-bookmark in directives file syntax

- docs/usage/directives/configurations/_category_.json
- docs/usage/directives/directives-server.md
- docs/usage/directives/firewall/_category_.json
- docs/usage/directives/where-to-store.md
[Documentation] Directives Server
> [Documentation] Directives Server

- base-system/prepare.sh
Copying apt preferences before apt install
> Copying apt preferences before apt install

- software-modules/programming/eclipse/eclipse.desktop
- software-modules/programming/eclipse/eclipse.sh
Updating eclipse software files
This PR
* Updates eclipse to download the tar file from the eclipseide site instead of a local file in the software folder
> Updating eclipse software files

- docs/about/where-is-being-used.md
- docs/about/who-is-supporting-us.md
- docs/development/curret-goals.md
Adding TODO docs
Quick PR to add some TODO docs and don't forget about them in the future. Not sure on when we'll be able to write them, but just to keep track of them.
Probably we need to prioritize the 'Where is huronOS being used' as we're becoming the official OS of the Mexican Olympiad of Informatics.
> Adding TODO docs

- docs/usage/directives/configurations/events-and-contests.md
- docs/usage/how-to-install.md
- docs/usage/syncing-instances.md
[Documentation] Fixing in-docs links
> [Documentation] Fixing in-docs links

- base-system/prepare.sh
- base-system/tools/installer/install.sh
- base-system/usrroot/usr/lib/systemd/system/hsync.service
- base-system/usrroot/usr/lib/systemd/system/ipman.service
- base-system/usrroot/usr/sbin/ipman
- docs/usage/how-to-install.md
- software-modules/base/03-budgie/budgie.sh
[#20] Allows to define a static ip to use after booting
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/equetzal/huronOS-build-tools/pull/107).
* #173
* __->__ #107
> [#20] Allows to define a static ip to use after booting
